# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nfs/zfs-student-6/users/tmack/.brew/Cellar/cmake/3.8.1/bin/cmake

# The command to remove a file.
RM = /nfs/zfs-student-6/users/tmack/.brew/Cellar/cmake/3.8.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /nfs/zfs-student-6/users/tmack/Projects/AbstractVM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /nfs/zfs-student-6/users/tmack/Projects/AbstractVM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/nfs/zfs-student-6/users/tmack/.brew/Cellar/cmake/3.8.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/nfs/zfs-student-6/users/tmack/.brew/Cellar/cmake/3.8.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/zfs-student-6/users/tmack/Projects/AbstractVM/CMakeFiles /nfs/zfs-student-6/users/tmack/Projects/AbstractVM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/zfs-student-6/users/tmack/Projects/AbstractVM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named abstractvm

# Build rule for target.
abstractvm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abstractvm
.PHONY : abstractvm

# fast build rule for target.
abstractvm/fast:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/build
.PHONY : abstractvm/fast

ErrorHandle.o: ErrorHandle.cpp.o

.PHONY : ErrorHandle.o

# target to build an object file
ErrorHandle.cpp.o:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/ErrorHandle.cpp.o
.PHONY : ErrorHandle.cpp.o

ErrorHandle.i: ErrorHandle.cpp.i

.PHONY : ErrorHandle.i

# target to preprocess a source file
ErrorHandle.cpp.i:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/ErrorHandle.cpp.i
.PHONY : ErrorHandle.cpp.i

ErrorHandle.s: ErrorHandle.cpp.s

.PHONY : ErrorHandle.s

# target to generate assembly for a file
ErrorHandle.cpp.s:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/ErrorHandle.cpp.s
.PHONY : ErrorHandle.cpp.s

Stackstuff.o: Stackstuff.cpp.o

.PHONY : Stackstuff.o

# target to build an object file
Stackstuff.cpp.o:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/Stackstuff.cpp.o
.PHONY : Stackstuff.cpp.o

Stackstuff.i: Stackstuff.cpp.i

.PHONY : Stackstuff.i

# target to preprocess a source file
Stackstuff.cpp.i:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/Stackstuff.cpp.i
.PHONY : Stackstuff.cpp.i

Stackstuff.s: Stackstuff.cpp.s

.PHONY : Stackstuff.s

# target to generate assembly for a file
Stackstuff.cpp.s:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/Stackstuff.cpp.s
.PHONY : Stackstuff.cpp.s

VMFactory.o: VMFactory.cpp.o

.PHONY : VMFactory.o

# target to build an object file
VMFactory.cpp.o:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/VMFactory.cpp.o
.PHONY : VMFactory.cpp.o

VMFactory.i: VMFactory.cpp.i

.PHONY : VMFactory.i

# target to preprocess a source file
VMFactory.cpp.i:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/VMFactory.cpp.i
.PHONY : VMFactory.cpp.i

VMFactory.s: VMFactory.cpp.s

.PHONY : VMFactory.s

# target to generate assembly for a file
VMFactory.cpp.s:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/VMFactory.cpp.s
.PHONY : VMFactory.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/abstractvm.dir/build.make CMakeFiles/abstractvm.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... abstractvm"
	@echo "... ErrorHandle.o"
	@echo "... ErrorHandle.i"
	@echo "... ErrorHandle.s"
	@echo "... Stackstuff.o"
	@echo "... Stackstuff.i"
	@echo "... Stackstuff.s"
	@echo "... VMFactory.o"
	@echo "... VMFactory.i"
	@echo "... VMFactory.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

